services:

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: Trainee-backend
    environment:
      - JWT_SECRET=your_secret_key_here
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRATION=60
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    networks:
      - trainee_condoconnect-network
    restart: unless-stopped
    # command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

networks:
  trainee_condoconnect-network:
    driver: bridge
