services:
  postgres:
    image: postgres:15
    container_name: Trainee-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: StrongP@ssw0rd123!
      POSTGRES_DB: TecnimicPBX
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./CreateDataforDatabase.SQL:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - trainee-network
    restart: unless-stopped

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: Trainee-backend
    environment:
      - DATABASE_URL=postgresql://postgres:StrongP@ssw0rd123!@postgres:5432/TecnimicPBX
      - JWT_SECRET=your_secret_key_here
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRATION=60
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    networks:
      - trainee-network
    restart: unless-stopped

  

  db-init:
    image: postgres:15
    depends_on:
      - postgres
    entrypoint: ["psql", "-h", "postgres", "-U", "postgres", "-d", "TecnimicPBX", "-f", "/docker-entrypoint-initdb.d/01-init.sql"]
    environment:
      PGPASSWORD: StrongP@ssw0rd123!
    volumes:
      - ./CreateDataforDatabase.SQL:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - trainee-network

networks:
  trainee-network:
    driver: bridge

volumes:
  postgres_data: